/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const ChecklistItem = IDL.Record({
  'name' : IDL.Text,
  'photo' : IDL.Opt(ExternalBlob),
});
export const StoreChecklistEntry = IDL.Record({
  'id' : IDL.Text,
  'submitter' : IDL.Principal,
  'storeName' : IDL.Text,
  'timestamp' : IDL.Int,
  'items' : IDL.Vec(ChecklistItem),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createChecklistEntry' : IDL.Func(
      [IDL.Text, IDL.Vec(ChecklistItem)],
      [IDL.Text],
      [],
    ),
  'filterEntriesByStoreName' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(StoreChecklistEntry)],
      [],
    ),
  'filterEntriesByUser' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(StoreChecklistEntry)],
      [],
    ),
  'getAllChecklistEntries' : IDL.Func([], [IDL.Vec(StoreChecklistEntry)], []),
  'getAllEntriesSortedByNewestEntries' : IDL.Func(
      [],
      [IDL.Vec(StoreChecklistEntry)],
      [],
    ),
  'getAllEntriesSortedByStore' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(StoreChecklistEntry)],
      [],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getEntry' : IDL.Func([IDL.Text], [IDL.Opt(StoreChecklistEntry)], []),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'hasAdminRole' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'ping' : IDL.Func([], [IDL.Text], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const ChecklistItem = IDL.Record({
    'name' : IDL.Text,
    'photo' : IDL.Opt(ExternalBlob),
  });
  const StoreChecklistEntry = IDL.Record({
    'id' : IDL.Text,
    'submitter' : IDL.Principal,
    'storeName' : IDL.Text,
    'timestamp' : IDL.Int,
    'items' : IDL.Vec(ChecklistItem),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createChecklistEntry' : IDL.Func(
        [IDL.Text, IDL.Vec(ChecklistItem)],
        [IDL.Text],
        [],
      ),
    'filterEntriesByStoreName' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(StoreChecklistEntry)],
        [],
      ),
    'filterEntriesByUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(StoreChecklistEntry)],
        [],
      ),
    'getAllChecklistEntries' : IDL.Func([], [IDL.Vec(StoreChecklistEntry)], []),
    'getAllEntriesSortedByNewestEntries' : IDL.Func(
        [],
        [IDL.Vec(StoreChecklistEntry)],
        [],
      ),
    'getAllEntriesSortedByStore' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(StoreChecklistEntry)],
        [],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getEntry' : IDL.Func([IDL.Text], [IDL.Opt(StoreChecklistEntry)], []),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'hasAdminRole' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'ping' : IDL.Func([], [IDL.Text], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };